### ISSUE TITLE
users 페이지에서 user 별 위치가 `seoul`로 동일하게 나옵니다.

### ISSUE THREAD

**Issue by SDuck4** [subicura/mysetting.io#1]
저는 지역을 `Daejeon, South Korea` 으로 설정했는데, 목록에서는 `seoul`로 나와요.

**Comment by SDuck4** [comment]
수정됐내요. 감사합니다. :)

**Comment by subicura** [comment]
제보 감사합니다 ;ㅁ; 급하게 만들었더니 버그가 있네요..
