### ISSUE TITLE
슬라이드의 일부 이미지가 변환에 실패하였습니다.

### ISSUE THREAD

**Issue by wesky93** [subicura/mysetting.io#10]
https://mysetting.io/slides/back-to-the-basic-lambda
이 슬라이드의 일부 이미지가 아래와 같이 변환 실패하여 제대로 노출이 안됩니다.

<img width="1035" alt="2022-10-12_21-33-57" src="https://user-images.githubusercontent.com/5326335/195343704-07dfc82f-c478-4454-8eab-9c789fef90fa.png">

**Comment by subicura** [comment]
사용중 불편을 드려 죄송합니다. 확인 후 말씀드리겠습니다!

**Comment by subicura** [comment]
수정하였습니다. 제보 감사합니다 👏

**Comment by jonoh0224** [comment]
@subicura 안녕하세요~ 우연히 위 @wesky93 님 발표자료 공유 받은 1인으로 제가 겪고있는 현상과 유사한 pdf변환 실패 케이스로 보여서 실례를 무릅쓰고 문의 남겨봅니다. 혹시 사유가 어떤 것이었는지 간략히 공유해주실 수 있을까요~?ㅠ
참고로 저는 lambda nodejs 환경에서 pdf2pic 라이브러리 사용하여 pdf 이미지로 변환하여 s3로 업로드하는 방식으로 구현 중입니다.

**Comment by subicura** [comment]
@jonoh0224 안녕하세요! mysetting도 동일하게 lambda nodejs에 pdf2pic 라이브러리를 사용하고 있습니다.
문제의 원인은 정확히 찾지 못했지만 기존에 base64로 export 후 s3 upload 방식에서, 이미지 파일로 export 후 이미지 파일을 s3 upload 하는 방식으로 변경하여 해결하였습니다. 도움되길 바랍니다!

**Comment by jonoh0224** [comment]
@subicura 아 정말 감사합니다 ㅠ base64 인코딩 문제인 것 같았는데 쉽게 해결 방안이 보이지 않아 고민이었거든요 ㅠ 
말씀 주신 방법대로 적용하니 바로 해결되었습니다! 이런 방법이 있었네요..ㅎㅎ 
큰 도움 주셔서 정말 감사 드립니다!
