### ISSUE TITLE
개발환경 추가시 모달팝업의 타이틀이 "기술 추가"로 고정

### ISSUE THREAD

**Issue by hunj** [subicura/mysetting.io#2]
# Current
개발환경 내용 추가 시 모달 팝업의 타이틀이 `기술 추가` 로 고정되어 나옵니다:

예: OS 카테고리에서 "추가" 버튼 클릭 시 "기술 추가"로 출력:
![image](https://user-images.githubusercontent.com/3972717/117541729-3665a480-afe3-11eb-956d-6b98f8bb5261.png)

# Expected
모달 팝업의 타이틀이 `[클릭한 카테고리] 추가` 로 나오면 좋겠습니다.

예: OS 카테고리 "추가" 버튼 클릭 시 "OS 추가"로 출력

**Comment by subicura** [comment]
세부적인 부분인데 체크 감사합니다!
