### ISSUE TITLE
슬라이드 화면 전환 

### ISSUE THREAD

**Issue by lqez** [subicura/mysetting.io#3]
좋은 서비스 만들어주셔서 감사합니다.

슬라이드의 기본 전환 효과가 `slide` 인데, 와이드 모니터에서 장표 좌우로 검은 여백이 많은 상태에서 슬라이드 효과를 계속 보고 있으니, 내용에 집중하기가 다소 어렵다는 생각이 듭니다. 그래서 아래의 제안을 드려봅니다.

  1. 기본 전환 효과를 `효과 없음`으로 변경
  2. 사용자 지정 전환 효과를 업로드한 사용자가 해당 슬라이드에 지정한 설정으로 오버라이드

감사합니다!

**Comment by subicura** [comment]
큰 모니터 생각을 못했네요. 기본효과를 변경하는게 좋을 것 같습니디. 개선하도록 하겠습니다~

**Comment by subicura** [comment]
기본값 변경했습니다.
모바일 - slide
데스크탑 - none

**Comment by lqez** [comment]
제안 받아들여주셔서 감사합니다!
