### ISSUE TITLE
프로필 수정에서 인라인 에디팅

### ISSUE THREAD

**Issue by ChangJoo-Park** [subicura/mysetting.io#4]
우선 좋은 서비스 만들어주셔서 감사합니다

입력하면서 느낀 불편함을 말씀드립니다

## 발생한 페이지

https://mysetting.io/setting 프로필 수정 페이지를 사용하던 중 경험한 내용을 남깁니다

## 무엇이 문제인지

프로필 수정 화면에서 여러 정보를 입력하는 경우에 계속 마우스를 이동해서 다시 눌러야 하는 불편함이 있습니다.

## 어떻게 바뀌면 좋을지

추가 버튼을 누르면, 입력할 수 있는 `<input />` 으로 바뀌어 바로 입력할 수 있었으면 빠르게 내용을 채울 수 있을 것으로 보입니다.

예:

![image](https://user-images.githubusercontent.com/1451365/118422363-0b273780-b6fe-11eb-99c4-a8b0b4760f38.png)

이 이미지에서 new tag를 누르면 아래와 같이 변경됩니다.

![image](https://user-images.githubusercontent.com/1451365/118422375-137f7280-b6fe-11eb-9934-62eebf8df067.png)

포커스된 `<input />` 에서 엔터를 누르면 추가됩니다.

참고 URL : https://antdv.com/components/tag/

**Comment by subicura** [comment]
소중한 의견 감사합니다! 더 편하게 입력할 수 있도록 개선하겠습니다~

**Comment by subicura** [comment]
팝업대신 인라인 에디팅으로 적용되었습니다.

**Comment by ChangJoo-Park** [comment]
> 팝업대신 인라인 에디팅으로 적용되었습니다.

사용해봤는데 입력하기 정말 편해졌어요 감사합니다
