### ISSUE TITLE
프로필 수정 중 저장 문제

### ISSUE THREAD

**Issue by ChangJoo-Park** [subicura/mysetting.io#5]
## 발생한 페이지

https://mysetting.io/setting 프로필 수정 페이지를 사용하던 중 경험한 내용을 남깁니다

## 무엇이 문제인지

프로필을 처음 입력한 다음 다음에 들어갔을 때 추가 버튼을 눌러 추가하면 자동으로 저장되는 줄 착각하고 다른 페이지로 이동했습니다.

아래에 저장 버튼을 반드시 눌러야 저장이 됩니다.

입력할 것이 많은 세로 스크롤이 긴 페이지여서 윗부분을 수정하더라도 맨 아래에서 저장 버튼을 눌러야 합니다.

## 어떻게 바뀌었으면 좋을지

1. 스크롤이 상단에 있는 경우에도 저장 버튼이 보이면 필요한 내용을 수정한 다음 바로 저장 버튼을 누를 수 있을 것으로 생각됩니다.
2. 프로필 변경 후 바로, 또는 잠시 시간이 흐르면 자동으로 저장되어도 좋을 것 같습니다.

**Comment by subicura** [comment]
소중한 의견 감사합니다! 저장 ui를 개선해보겠습니다.

**Comment by subicura** [comment]
저장버튼을 항상 노출하도록 개선하였습니다.
