### ISSUE TITLE
슬라이드 PDF 변경이 불가합니다

### ISSUE THREAD

**Issue by lqez** [subicura/mysetting.io#6]
https://mysetting.io/slides/contrast-and-vector/edit

위 슬라이드의 오탈자를 수정하기 위해 새 PDF를 업로드 하려는데, 용량 초과나 기타 오류 없이 조용히 처리되고 파일 이름이 새 이름으로 바뀝니다.
페이지를 새로고침하면 다시 예전 이름으로 돌아가 있고, 변경되지 않습니다.

https://user-images.githubusercontent.com/579366/118459582-d84d6580-b736-11eb-8ba3-ca15f07ea80e.mov

**Comment by subicura** [comment]
슬라이드 변경후 저장을 눌러야 반영이 됩니다. UI를 좀 더 친절하게 바꿔야겠네요 ㅠ
지난번 PDF가 제대로 처리안되는 문제가 아직 해결이 안되어 해당 파일도 수동으로 변환하도록 하겠습니다~ 어떤 부분 수정되었는지 알 수 있을까요? 변환 후에 체크해보겠습니다.

**Comment by lqez** [comment]
@subicura 아! `변경하기`가 액션 버튼의 느낌이라 착각했습니다. 죄송합니다.
다시 저장을 눌러 `PROCESSING` 으로 넘어간 상태입니다. 답변 감사합니다.

**Comment by subicura** [comment]
해당 PDF가 아직 해결하지 못한 버그로 변환을 할 수 없습니다 ㅠ 따로 업데이트 하고 말씀드리겠습니다.

**Comment by subicura** [comment]
`슬라이드 변경하기`는 액션느낌이라 `슬라이드 다시 업로드`라고 하는게 더 명확해보이네요. 의견 감사합니다. 👍

**Comment by lqez** [comment]
> 어떤 부분 수정되었는지 알 수 있을까요? 변환 후에 체크해보겠습니다.

@subicura 페이지 전체가 수정된 부분은 없고, 대부분 오탈자와 줄바꿈 수정입니다.

**Comment by subicura** [comment]
변환 완료되었습니다. 수정부분 확인부탁드립니다~

https://mysetting.io/slides/contrast-and-vector

**Comment by lqez** [comment]
@subicura 감사합니다!
묘하게 jpg 화질이 떨어진 느낌적 느낌이지만, 다음에 `Re: 하루개발` 하러 가서 webp 적용해보면 재미있을 것 같습니다. 😆
