### ISSUE TITLE
navbar - 이미 프로필이 있어도 버튼 텍스트가 [프로필 만들기]로 표기됩니다.

### ISSUE THREAD

**Issue by hunj** [subicura/mysetting.io#7]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/3972717/119692134-2807ed00-be19-11eb-901e-d12ca431d4f6.png">

이미 프로필을 만들었는데도 `[프로필 만들기]` 로 표기됩니다. `수정` 혹은 `관리` 를 사용하면 조금 덜 햇갈릴 것 같습니다.

**Comment by subicura** [comment]
좋은 의견 감사합니다! `프로필 관리`로 변경하였습니다~
