### ISSUE TITLE
모바일 화면에서 프로필 관리 시 개발환경 추가 불가능

### ISSUE THREAD

**Issue by mystria** [subicura/mysetting.io#9]
발생 조건
안드로이드 크롬 앱 기준
모바일 > 로그인 > 메뉴 > 프로필 관리 > 개발환경 > 항목 추가

발생 내용
항목을 추가하기 위해서 '+추가'를 누를 경우 인라인으로 값을 입력할 수 있습니다. 
입력한 값을 항목으로 추가하기 위해서는 반드시 엔터키를 눌러 완료하여야 합니다.
그러나 모바일에 표시되는 키보드에 엔터키가 표시되지 않아 입력을 완료하지 못해 추가가 불가능 합니다.
엔터키 대신 "이동"키가 활성화 되는데, 이것을 누를 경우 "저장"이 수행됩니다.
(아이폰에서는 엔터가 가능한지 확인 하지 못했습니다.)
참고로 "기술"의 경우에는 추천되는 항목을 선택함으로써 입력을 완료할 수 있습니다.

수정 방향
인라인 입력창에서 엔터가 입력가능 하도록 하거나 입력 완료를 위한 다른 방법(버튼 등)이 필요합니다.

**Comment by subicura** [comment]
안녕하세요! 제보 감사합니다. enter 버튼이 노출되지 않는 경우가 있어 입력 버튼을 추가했습니다. 👏
